version: 0.2

phases:
  install:
    commands:
      - npm i
  pre_build:
    commands:
      - echo "NEXT_PUBLIC_COGNITO_CLIENT_ID=${NEXT_PUBLIC_COGNITO_CLIENT_ID}" >> .env.production
      - echo "NEXT_PUBLIC_COGNITO_USER_POOL_ID=${NEXT_PUBLIC_COGNITO_USER_POOL_ID}" >> .env.production
      - echo "NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}" >> .env.production
  build:
    commands:
      - npm run build
      
artifacts:
  type: zip
  files:
    - "**/*"
  base-directory: out